### ISSUE TITLE
PyPy3 tests fail with ZEO 6.0

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.zodbrecipes#8]
### What I did:

GHA is running the tests for PyPy3 and fails since using ZEO 6.0.0.

### What I expect to happen:

Successful tests.

### What actually happened:

Failures in strange ways, see https://github.com/zopefoundation/zc.zodbrecipes/actions/runs/6995392867/job/19045169682

### What version of Python and Zope/Addons I am using:

* PyPy3
* `master` branch of `zc.zodbrecipes`.

Sorry for the broad CC but this package is not listed as maintained, so I do not know if it is still actually used.
@zopefoundation/developers Is anyone interested in fixing this issue? Otherwise I'd drop PyPy3 support.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2023-11-27 23:04 -0800:
> ...
>GHA is running the tests for PyPy3 and fails since using ZEO 6.0.0.
> ...
>Failures in strange ways, see https://github.com/zopefoundation/zc.zodbrecipes/actions/runs/6995392867/job/19045169682

I tried to reproduce the problem locally -- and failed:
the PyPy3 tests succeeded with ZEO 6.0.0.

The failure is really strange (as you wrote)
because the creation of the deployment files is
simply an `open(..., "w").write(template % confdict)`
and therefore independent from any ZEO version.
The test output seems to indicate that the deployment file exists
but is empty -- which seems impossible.

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2023-11-28 09:22 +0100:
>Michael Howitz wrote at 2023-11-27 23:04 -0800:
>> ...
>>GHA is running the tests for PyPy3 and fails since using ZEO 6.0.0.
>> ...
>>Failures in strange ways, see https://github.com/zopefoundation/zc.zodbrecipes/actions/runs/6995392867/job/19045169682
>
>I tried to reproduce the problem locally -- and failed:
>the PyPy3 tests succeeded with ZEO 6.0.0.
>
>The failure is really strange (as you wrote)
>because the creation of the deployment files is
>simply an `open(..., "w").write(template % confdict)`
>and therefore independent from any ZEO version.
>The test output seems to indicate that the deployment file exists
>but is empty -- which seems impossible.

Found the problem: `open(...).write(...)` is not PyPY3 conform,
because the buffer is flushed only at the time of the next
garbage collection.
`zc.zodbrecipes` needs corresponding fixes.

**Comment by leorochael** [comment]
And the proper fix would be to explicitly close the file after writing, so we don't leak file descriptors unnecessarily for the gc to collect.

My preferred option for doing that is also an one-liner [using `pathlib.Path.write()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_text). For ex. replacing:

```python
        open(zeo_conf_path, 'w').write(str(zeo_conf))
```

With:

```python
        Path(zeo_conf_path).write_text(str(zeo_conf))
```

We should also replace `open(...).read()` with `Path(...).read_text()` while [we're](https://github.com/zopefoundation/zc.zodbrecipes/blob/9406c9c56285297b18232b6fb89f00c8b36f2a59/setup.py#L8) at [it](https://github.com/zopefoundation/zc.zodbrecipes/blob/9406c9c56285297b18232b6fb89f00c8b36f2a59/src/zc/zodbrecipes/__init__.py#L224).

**Comment by d-maurer** [comment]
Leonardo Rochael Almeida wrote at 2023-11-28 04:18 -0800:
>And the proper fix would be to explicitly close the file after writing, so we don't leak file descriptors unnecessarily for the gc to collect.

The recioe runs only for a very short time -- thus, if we
force a garbage collection at the recipe end, having used
a few file descriptors longer than necessary should not really matter.

Of course, I would approve a PR with the "proper" fix.
Are you interested to create such a PR?
